name: evo2
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-12.8.0
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - binutils_impl_linux-aarch64=2.40=h4fb32a3_0
  - binutils_linux-aarch64=2.40=h1f91aba_9
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.11.4=hd43f75c_0
  - cuda-cccl_linux-aarch64=12.8.55=0
  - cuda-command-line-tools=12.8.0=0
  - cuda-compiler=12.8.0=0
  - cuda-crt-dev_linux-aarch64=12.8.61=0
  - cuda-crt-tools=12.8.61=0
  - cuda-cudart=12.8.57=0
  - cuda-cudart-dev=12.8.57=0
  - cuda-cudart-dev_linux-aarch64=12.8.57=0
  - cuda-cudart-static=12.8.57=0
  - cuda-cudart-static_linux-aarch64=12.8.57=0
  - cuda-cudart_linux-aarch64=12.8.57=0
  - cuda-cuobjdump=12.8.55=0
  - cuda-cupti=12.8.57=0
  - cuda-cupti-dev=12.8.57=0
  - cuda-cuxxfilt=12.8.55=0
  - cuda-driver-dev=12.8.57=0
  - cuda-driver-dev_linux-aarch64=12.8.90=0
  - cuda-gdb=12.8.55=0
  - cuda-libraries=12.8.0=0
  - cuda-libraries-dev=12.8.0=0
  - cuda-nvcc=12.8.61=0
  - cuda-nvcc-dev_linux-aarch64=12.8.61=0
  - cuda-nvcc-impl=12.8.61=0
  - cuda-nvcc-tools=12.8.61=0
  - cuda-nvcc_linux-aarch64=12.8.61=0
  - cuda-nvdisasm=12.8.55=0
  - cuda-nvml-dev=12.8.55=0
  - cuda-nvprune=12.8.55=0
  - cuda-nvrtc=12.8.61=0
  - cuda-nvrtc-dev=12.8.61=0
  - cuda-nvtx=12.8.55=0
  - cuda-nvvm-dev_linux-aarch64=12.8.61=0
  - cuda-nvvm-impl=12.8.61=0
  - cuda-nvvm-tools=12.8.61=0
  - cuda-profiler-api=12.8.55=0
  - cuda-sanitizer-api=12.8.55=0
  - cuda-tools=12.8.0=0
  - cuda-version=12.8=3
  - cuda-visual-tools=12.8.0=0
  - cudnn=9.14.0.64=h2e37800_0
  - dbus=1.16.2=h6a16351_0
  - expat=2.7.1=h419075a_0
  - fontconfig=2.15.0=h8dda3cd_1
  - freetype=2.13.3=h6df46f4_0
  - gcc_impl_linux-aarch64=12.3.0=h3d98823_13
  - gcc_linux-aarch64=12.3.0=ha52a6ea_9
  - gds-tools=1.13.0.11=0
  - gmp=6.3.0=h419075a_0
  - gxx_impl_linux-aarch64=12.3.0=hba91e99_13
  - gxx_linux-aarch64=12.3.0=h9d1f256_9
  - icu=73.1=h419075a_0
  - kernel-headers_linux-aarch64=4.14.214=h1cb168f_14
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libcublas=12.8.3.14=0
  - libcublas-dev=12.8.3.14=0
  - libcudnn=9.14.0.64=hfd19673_0
  - libcudnn-dev=9.14.0.64=h2e37800_0
  - libcufft=11.3.3.41=0
  - libcufft-dev=11.3.3.41=0
  - libcufile=1.13.0.11=0
  - libcufile-dev=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcurand-dev=10.3.9.55=0
  - libcusolver=11.7.2.55=0
  - libcusolver-dev=11.7.2.55=0
  - libcusparse=12.5.7.53=0
  - libcusparse-dev=12.5.7.53=0
  - libexpat=2.7.1=hfae3067_0
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=he277a41_7
  - libgcc-devel_linux-aarch64=12.3.0=h6144e03_113
  - libgcc-ng=15.2.0=he9431aa_7
  - libglib=2.84.4=h481f47d_0
  - libgomp=15.2.0=he277a41_7
  - libiconv=1.16=h998d150_3
  - libnpp=12.3.3.65=0
  - libnpp-dev=12.3.3.65=0
  - libnsl=2.0.0=h998d150_0
  - libnvfatbin=12.8.55=0
  - libnvfatbin-dev=12.8.55=0
  - libnvjitlink=12.8.61=1
  - libnvjitlink-dev=12.8.61=1
  - libnvjpeg=12.3.5.57=0
  - libnvjpeg-dev=12.3.5.57=0
  - libpng=1.6.50=h01b5ae2_0
  - libsanitizer=12.3.0=h57e2e72_13
  - libsqlite=3.50.4=h022381a_0
  - libstdcxx=15.2.0=h3f4de04_7
  - libstdcxx-devel_linux-aarch64=12.3.0=h6144e03_113
  - libstdcxx-ng=15.2.0=hf1166c9_7
  - libuuid=2.41.2=h3e4203c_0
  - libxcb=1.17.0=hf66535e_0
  - libxkbcommon=1.9.1=h417a37e_0
  - libxml2=2.13.9=h729a2f8_0
  - libzlib=1.3.1=h998d150_0
  - nccl=2.28.7=h1ed1a18_0
  - ncurses=6.5=h419075a_0
  - nsight-compute=2025.1.0.14=0
  - nspr=4.37=he858ca9_0
  - nss=3.117=h860adcc_0
  - nvtx=0.2.13=py312hefbd42c_1
  - openssl=3.5.4=h8e36d6e_0
  - pcre2=10.46=h1746348_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.12.0=h43d1f9e_0_cpython
  - python_abi=3.12=8_cp312
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py312hd43f75c_0
  - sqlite=3.50.2=h998d150_1
  - sysroot_linux-aarch64=2.26=h4744778_14
  - tk=8.6.15=h987d8db_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hd43f75c_0
  - xkeyboard-config=2.44=h998d150_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.1
      - biopython==1.86
      - certifi==2025.10.5
      - click==8.3.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - einops==0.8.1
      - evo2==0.4.0
      - executing==2.2.1
      - filelock==3.19.1
      - flash-attn==2.8.0.post2
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.8.90
      - onnx==1.19.1
      - onnx-ir==0.1.12
      - onnxscript==0.5.4
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rich==14.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - torch==2.9.0+cu128
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformer-engine==2.8.0
      - transformer-engine-cu12==2.8.0
      - transformer-engine-torch==2.8.0
      - triton==3.5.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - vtx==1.0.7
      - wcwidth==0.2.14
      - zipp==3.23.0
prefix: /home/wlt2025/anaconda3/envs/evo2
